export const COMMIT = "5e7911b3d703804f7a9065f5edcd99e1a5efb1cf";

export const VERSION = "master";

export const SERIES = {
  "ADV": "ADV",
  "E": "e",
  "L": "L",
  "M": "M",
  "MISC": "misc",
  "NEO": "neo",
  "PCG": "PCG",
  "PMCG": "PMCG",
  "S": "S",
  "SM": "SM",
  "SV": "SV",
  "VS": "VS",
  "WEB": "web",
  "XY": "XY",
  "XYB": "XYb"
} as const;

export const SERIES_IDS = [
  "ADV",
  "L",
  "M",
  "PCG",
  "PMCG",
  "S",
  "SM",
  "SV",
  "VS",
  "XY",
  "XYb",
  "e",
  "misc",
  "neo",
  "web"
] as const;

export const SETS = {
  "E": {
    "E1": "E1",
    "E2": "E2",
    "E3": "E3",
    "E4": "E4",
    "E5": "E5"
  },
  "M": {
    "M1L": "M1L",
    "M1S": "M1S",
    "M2": "M2",
    "M2A": "M2a",
    "M3": "M3",
    "M4": "M4",
    "M5": "M5",
    "M6": "M6",
    "MC": "MC",
    "M_P": "M-P"
  },
  "MISC": {
    "MISCELLANEOUS_PROMOS": "Miscellaneous Promos"
  },
  "NEO": {
    "NEO1": "neo1",
    "NEO2": "neo2",
    "NEO3": "neo3",
    "NEO4": "neo4"
  },
  "PCG": {
    "PCG1": "PCG1",
    "PCG2": "PCG2",
    "PCG3": "PCG3",
    "PCG4": "PCG4",
    "PCG5": "PCG5",
    "PCG6": "PCG6",
    "PCG7": "PCG7",
    "PCG8": "PCG8",
    "PCG9": "PCG9"
  },
  "PMCG": {
    "PMCG1": "PMCG1",
    "PMCG2": "PMCG2",
    "PMCG3": "PMCG3",
    "PMCG4": "PMCG4",
    "PMCG5": "PMCG5",
    "PMCG6": "PMCG6"
  },
  "S": {
    "S10A": "S10a",
    "S10B": "S10b",
    "S10D": "S10D",
    "S10P": "S10P",
    "S11": "S11",
    "S11A": "S11a",
    "S12": "S12",
    "S12A": "S12a",
    "S4": "S4",
    "S4A": "S4a",
    "S5A": "S5a",
    "S5I": "S5I",
    "S5R": "S5R",
    "S6A": "S6a",
    "S6H": "S6H",
    "S6K": "S6K",
    "S7D": "S7D",
    "S7R": "S7R",
    "S8": "S8",
    "S8A": "S8a",
    "S8B": "S8b",
    "S9": "S9",
    "S9A": "S9a",
    "SC1A": "SC1a",
    "SC1B": "SC1b",
    "SC1D": "SC1D",
    "SC2A": "SC2a",
    "SC2B": "SC2b",
    "SC2D": "SC2D",
    "SCA": "SCA",
    "SCB": "SCB",
    "SCC": "SCC",
    "SCD": "SCD",
    "SDL": "SDL",
    "SDM": "SDM",
    "SDP": "SDP",
    "SH": "SH",
    "SI": "SI",
    "SJ": "SJ",
    "SK": "SK",
    "SLD": "SLD",
    "SLL": "SLL",
    "SN": "SN",
    "SP5": "SP5",
    "SP6": "SP6",
    "SPD": "SPD",
    "SPZ": "SPZ",
    "S_P": "S-P"
  },
  "SM": {
    "CSMPIC": "CSMPiC",
    "SM10": "SM10",
    "SM10A": "SM10a",
    "SM10B": "SM10b",
    "SM11": "SM11",
    "SM11A": "SM11a",
    "SM11B": "SM11b",
    "SM12": "SM12",
    "SM12A": "SM12a",
    "SM1M": "SM1M",
    "SM1P": "SM1p",
    "SM1S": "SM1S",
    "SM2K": "SM2K",
    "SM2L": "SM2L",
    "SM2P": "SM2p",
    "SM3H": "SM3H",
    "SM3N": "SM3N",
    "SM3P": "SM3p",
    "SM4A": "SM4A",
    "SM4P": "SM4p",
    "SM4S": "SM4S",
    "SM5M": "SM5M",
    "SM5P": "SM5p",
    "SM5S": "SM5S",
    "SM6": "SM6",
    "SM6A": "SM6a",
    "SM6B": "SM6b",
    "SM7": "SM7",
    "SM7A": "SM7a",
    "SM7B": "SM7b",
    "SM8": "SM8",
    "SM8A": "SM8a",
    "SM8B": "SM8b",
    "SM9": "SM9",
    "SM9A": "SM9a",
    "SM9B": "SM9b"
  },
  "SV": {
    "SV10": "SV10",
    "SV11B": "SV11B",
    "SV11W": "SV11W",
    "SV1A": "SV1a",
    "SV1S": "SV1S",
    "SV1V": "SV1V",
    "SV2A": "SV2a",
    "SV2D": "SV2D",
    "SV2P": "SV2P",
    "SV3": "SV3",
    "SV3A": "SV3a",
    "SV3S": "SV3s",
    "SV4A": "SV4a",
    "SV4K": "SV4K",
    "SV4M": "SV4M",
    "SV4S": "SV4s",
    "SV5A": "SV5a",
    "SV5K": "SV5K",
    "SV5M": "SV5M",
    "SV5S": "SV5s",
    "SV6": "SV6",
    "SV6A": "SV6a",
    "SV6S": "SV6s",
    "SV7": "SV7",
    "SV7A": "SV7a",
    "SV7S": "SV7s",
    "SV8": "SV8",
    "SV8A": "SV8a",
    "SV8S": "SV8s",
    "SV9": "SV9",
    "SV9A": "SV9a",
    "SV9S": "SV9s",
    "SVAL": "SVAL",
    "SVAM": "SVAM",
    "SVAW": "SVAW",
    "SVB": "SVB",
    "SVC": "SVC",
    "SVD": "SVD",
    "SVDS": "SVDs",
    "SVEL": "SVEL",
    "SVEM": "SVEM",
    "SVF": "SVF",
    "SVHK": "SVHK",
    "SVHM": "SVHM",
    "SVK": "SVK",
    "SVLN": "SVLN",
    "SVLS": "SVLS",
    "SVP1": "SVP1",
    "SV_P": "SV-P"
  },
  "VS": {
    "VS1": "VS1"
  },
  "WEB": {
    "WEB1": "web1"
  },
  "XY": {
    "CP1": "CP1",
    "CP2": "CP2"
  }
} as const;

export const SET_IDS = [
  "CP1",
  "CP2",
  "CSMPiC",
  "E1",
  "E2",
  "E3",
  "E4",
  "E5",
  "M-P",
  "M1L",
  "M1S",
  "M2",
  "M2a",
  "M3",
  "M4",
  "M5",
  "M6",
  "MC",
  "Miscellaneous Promos",
  "PCG1",
  "PCG2",
  "PCG3",
  "PCG4",
  "PCG5",
  "PCG6",
  "PCG7",
  "PCG8",
  "PCG9",
  "PMCG1",
  "PMCG2",
  "PMCG3",
  "PMCG4",
  "PMCG5",
  "PMCG6",
  "S-P",
  "S10D",
  "S10P",
  "S10a",
  "S10b",
  "S11",
  "S11a",
  "S12",
  "S12a",
  "S4",
  "S4a",
  "S5I",
  "S5R",
  "S5a",
  "S6H",
  "S6K",
  "S6a",
  "S7D",
  "S7R",
  "S8",
  "S8a",
  "S8b",
  "S9",
  "S9a",
  "SC1D",
  "SC1a",
  "SC1b",
  "SC2D",
  "SC2a",
  "SC2b",
  "SCA",
  "SCB",
  "SCC",
  "SCD",
  "SDL",
  "SDM",
  "SDP",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SLD",
  "SLL",
  "SM10",
  "SM10a",
  "SM10b",
  "SM11",
  "SM11a",
  "SM11b",
  "SM12",
  "SM12a",
  "SM1M",
  "SM1S",
  "SM1p",
  "SM2K",
  "SM2L",
  "SM2p",
  "SM3H",
  "SM3N",
  "SM3p",
  "SM4A",
  "SM4S",
  "SM4p",
  "SM5M",
  "SM5S",
  "SM5p",
  "SM6",
  "SM6a",
  "SM6b",
  "SM7",
  "SM7a",
  "SM7b",
  "SM8",
  "SM8a",
  "SM8b",
  "SM9",
  "SM9a",
  "SM9b",
  "SN",
  "SP5",
  "SP6",
  "SPD",
  "SPZ",
  "SV-P",
  "SV10",
  "SV11B",
  "SV11W",
  "SV1S",
  "SV1V",
  "SV1a",
  "SV2D",
  "SV2P",
  "SV2a",
  "SV3",
  "SV3a",
  "SV3s",
  "SV4K",
  "SV4M",
  "SV4a",
  "SV4s",
  "SV5K",
  "SV5M",
  "SV5a",
  "SV5s",
  "SV6",
  "SV6a",
  "SV6s",
  "SV7",
  "SV7a",
  "SV7s",
  "SV8",
  "SV8a",
  "SV8s",
  "SV9",
  "SV9a",
  "SV9s",
  "SVAL",
  "SVAM",
  "SVAW",
  "SVB",
  "SVC",
  "SVD",
  "SVDs",
  "SVEL",
  "SVEM",
  "SVF",
  "SVHK",
  "SVHM",
  "SVK",
  "SVLN",
  "SVLS",
  "SVP1",
  "VS1",
  "neo1",
  "neo2",
  "neo3",
  "neo4",
  "web1"
] as const;

export const CARD_ILLUSTRATORS = {
  "575381": "575381",
  "BIG_MAMA_TAGAWA": "\"Big Mama\" Tagawa",
  "0313": "0313",
  "2020_PIKACHU_PROJECT": "2020 Pikachu Project",
  "5BAN_GRAPHICS": "5ban Graphics",
  "AKIRA_EGAWA": "AKIRA EGAWA",
  "AYUMI_ODASHIMA": "AYUMI ODASHIMA",
  "ACORVIART": "Acorviart",
  "AKINO_FUKUJI": "Akino Fukuji",
  "AKIRA_KOMAYAMA": "Akira Komayama",
  "ALIYA_CHEN": "Aliya Chen",
  "AMELICART": "Amelicart",
  "ANDERSON": "Anderson",
  "ANESAKI_DYNAMIC": "Anesaki Dynamic",
  "APIOS": "Apios",
  "ARAI_KIRIKO": "Arai Kiriko",
  "ASAKO_ITO": "Asako Ito",
  "ATSUKO_NISHIDA": "Atsuko Nishida",
  "ATSUSHI_FURUSAWA": "Atsushi Furusawa",
  "ATSUYA_UKI": "Atsuya Uki",
  "AVEC_YOKO": "Avec Yoko",
  "AYA_KUSUBE": "Aya Kusube",
  "AYAKA_YOSHIDA": "Ayaka Yoshida",
  "AYAKO_OZAKI": "Ayako Ozaki",
  "AYAKO_YOSHIDA": "Ayako Yoshida",
  "BUN_TOUJO": "Bun Toujo",
  "CHORISO": "CHORISO",
  "CONA_NITANDA": "Cona Nitanda",
  "CONCEPTLAB": "ConceptLab",
  "DAG_INC": "D.A.G Inc.",
  "DOM": "DOM",
  "DEMIZUPOSUKA": "DemizuPosuka",
  "DSUKE": "Dsuke",
  "EBILA": "Ebila",
  "EMI_ANDO": "Emi Ando",
  "EN_MORIKURA": "En Morikura",
  "ERI_KAMEI": "Eri Kamei",
  "ERI_YAMAKI": "Eri Yamaki",
  "ESKE_YOSHINOB": "Eske Yoshinob",
  "FELICIA_CHEN": "Felicia Chen",
  "FUJIMOTO_GOLD": "Fujimoto Gold",
  "FUMIE_KITTAKA": "Fumie Kittaka",
  "FUZICHOCO": "Fuzichoco",
  "GAME_FREAK_INC": "GAME FREAK inc.",
  "GIDORA": "GIDORA",
  "GOSSAN": "GOSSAN",
  "GOTO_MINORI": "GOTO minori",
  "GAPAO": "Gapao",
  "GEMI": "Gemi",
  "HACCAN": "HACCAN",
  "HAGIYA_KAORU": "HAGIYA Kaoru",
  "HICO_KIM": "HICO KIM",
  "HYOGONOSUKE": "HYOGONOSUKE",
  "HACHINANA": "Hachinana",
  "HAJIME_KUSAJIMA": "Hajime Kusajima",
  "HARU_AKASAKA": "Haru Akasaka",
  "HARUKO_ICHIKAWA": "Haruko Ichikawa",
  "HASEGAWA_SAKI": "Hasegawa Saki",
  "HASUNO": "Hasuno",
  "HATAYA": "Hataya",
  "HEISUKE_KITAZAWA": "Heisuke Kitazawa",
  "HIDEAKI_HAKOZAKI": "Hideaki Hakozaki",
  "HIDEKI_ISHIKAWA": "Hideki Ishikawa",
  "HIROKI_ASANUMA": "Hiroki Asanuma",
  "HIROMICHI_SUGIYAMA": "Hiromichi Sugiyama",
  "HIRONOBU_YOSHIDA": "Hironobu Yoshida",
  "HIROTAKA_MARUFUJI": "Hirotaka Marufuji",
  "HIROYUKI_YAMAMOTO": "Hiroyuki Yamamoto",
  "HISAO_NAKAMURA": "Hisao Nakamura",
  "HITOSHI_ARIGA": "Hitoshi Ariga",
  "HOSHINO_KURO": "Hoshino KURO",
  "HUANG_TZU_EN": "Huang Tzu En",
  "IKEDA_SAKI": "IKEDA Saki",
  "INOSE_YUKIE": [
    "Inose yukie",
    "inose yukie"
  ],
  "IORI_SUZUKI": "Iori Suzuki",
  "IWAMOTO05": "Iwamoto05",
  "IZUCCH": "Izucch",
  "JAMES_TURNER": "James Turner",
  "JERKY": "Jerky",
  "JIRO_SASUMO": "Jiro Sasumo",
  "JIRO_SASUNO": "Jiro Sasuno",
  "JULIE_HANG": "Julie Hang",
  "JUMPEI_AKASAKA": "Jumpei Akasaka",
  "JUNE": "June",
  "JUNSEI_KUNINOBU": "Junsei Kuninobu",
  "KEIICHIRO_ITO": "KEIICHIRO ITO",
  "KG_2000": "KG-2000",
  "KIYOTAKA_OSHIYAMA": "KIYOTAKA OSHIYAMA",
  "KYUPIYAMA": "KYUPIYAMA",
  "KAGEMARU_HIMENO": "Kagemaru Himeno",
  "KAMOME_SHIRAHAMA": "Kamome Shirahama",
  "KANAKO_EO": "Kanako Eo",
  "KANAMI_OGATA": "Kanami Ogata",
  "KANNNU": "Kannnu",
  "KARIYA": "Kariya",
  "KATSUNORI_SATO": "Katsunori Sato",
  "KATSURA_TABATA": "Katsura Tabata",
  "KAZUHISA_URAGAMI": "Kazuhisa Uragami",
  "KAZUKI_MINAMI": "Kazuki Minami",
  "KAZUMA_KODA": "Kazuma Koda",
  "KAZUMASA_YASUKUNI": "Kazumasa Yasukuni",
  "KEDAMAHADAITAI_YAWARAKAI": "Kedamahadaitai Yawarakai",
  "KEIJI_KINEBUCHI": "Keiji Kinebuchi",
  "KEISIN": "Keisin",
  "KEISUKE_AZUMA": "Keisuke Azuma",
  "KEN_IKUJI": "Ken Ikuji",
  "KEN_SUGIMORI": "Ken Sugimori",
  "KENICHI_YAMAGUCHI": "Kenichi Yamaguchi",
  "KENJI_KINEBUCHI": "Kenji Kinebuchi",
  "KENT_KANETSUNA": "Kent Kanetsuna",
  "KINU_NISHIMURA": "Kinu Nishimura",
  "KOJI_NAKATA": "Koji Nakata",
  "KOUKI_SAITOU": "Kouki Saitou",
  "KOZUKI_MINAMI": "Kozuki Minami",
  "KRGC": "Krgc",
  "KURATA_SO": "Kurata So",
  "KUROIMORI": "Kuroimori",
  "KYOKO_UMEMOTO": "Kyoko Umemoto",
  "LINNE": "LINNE",
  "LEE_HYUNJUNG": "Lee HyunJung",
  "LIGTON": "Ligton",
  "MAHOU": "MAHOU",
  "MARINA_CHIKAZAWA": "MARINA Chikazawa",
  "MINAMINAMI_TAKE": "MINAMINAMI Take",
  "MPC_FILM": "MPC Film",
  "MUGENUP": "MUGENUP",
  "MAKURA_TAMI": "Makura Tami",
  "MANA_IBE": "Mana Ibe",
  "MASA": "Masa",
  "MASAKAZU_FUKUDA": "Masakazu Fukuda",
  "MASAKO_TOMII": "Masako Tomii",
  "MASAKO_YAMASHITA": "Masako Yamashita",
  "MEGUMI_HIGUCHI": "Megumi Higuchi",
  "MEGUMI_MIZUTANI": "Megumi Mizutani",
  "MEKAYU": [
    "Mekayu",
    "Mékayu"
  ],
  "MIDORI_HARADA": "Midori Harada",
  "MIKA_PIKAZO": "Mika Pikazo",
  "MIKI_TANAKA": "Miki Tanaka",
  "MINA_NAKAI": "Mina Nakai",
  "MINAHAMU": "Minahamu",
  "MINATO": "Minato",
  "MISA_TSUTSUI": "Misa Tsutsui",
  "MISAKI_HASHIMOTO": "Misaki Hashimoto",
  "MITSUHIRO_ARITA": "Mitsuhiro Arita",
  "MIZUE": "Mizue",
  "MORI_YUU": "Mori Yuu",
  "MOTOFUMI_FUJIWARA": "Motofumi Fujiwara",
  "MOUSHO": "Mousho",
  "MUGI_HAMADA": "Mugi Hamada",
  "N_DESIGN_INC": "N-DESIGN Inc.",
  "NC_EMPIRE": "NC Empire",
  "NABANA_KENSAKU": "Nabana Kensaku",
  "NABATAME_KAZUTAKA": "Nabatame Kazutaka",
  "NAGOMI_NIJO": "Nagomi Nijo",
  "NAKAMURA_IPPAN": "Nakamura Ippan",
  "NAOKI_SAITO": "Naoki Saito",
  "NAOYO_KIMURA": "Naoyo Kimura",
  "NARANO": "Narano",
  "NARUMI_SATO": "Narumi Sato",
  "NATSUKO_SHOJI_ETE": "Natsuko Shoji été",
  "NATSUMI_MIYANOSE": "Natsumi Miyanose",
  "NATSUMI_YOSHIDA": "Natsumi Yoshida",
  "NELNAL": "Nelnal",
  "NISOTA_NISO": "Nisota Niso",
  "NOBUHIRO_IMAGAWA": "Nobuhiro Imagawa",
  "NOBUSAWAMOCHIPUYO": "Nobusawa/Mochipuyo",
  "NORIKO_UONO": "Noriko Uono",
  "NURIKABE": "Nurikabe",
  "OKACHEKE": "OKACHEKE",
  "OKUBO": "OKUBO",
  "OOYAMA": "OOYAMA",
  "ORBITALLINK_INC": "ORBITALLINK Inc.",
  "OKU": "Oku",
  "ORCA": "Orca",
  "OSWALDO_KATO": "Oswaldo KATO",
  "OUNISHI": "Ounishi",
  "PLANETA": "PLANETA",
  "PLANETA_HIIRAGI": "PLANETA Hiiragi",
  "PLANETA_IGARASHI": "PLANETA Igarashi",
  "PLANETA_MOCHIZUKI": "PLANETA Mochizuki",
  "PLANETA_OTANI": "PLANETA Otani",
  "PLANETA_TSUJI": "PLANETA Tsuji",
  "PLANETA_YAMASHITA": "PLANETA Yamashita",
  "PANI_KOBAYASHI": "Pani Kobayashi",
  "PO_SUZUKI": "Po-Suzuki",
  "Q_RAIS": "Q-rais",
  "REND": "REND",
  "REOSPIKEE": "REOspikee",
  "RAITA_KAZAMA": "Raita Kazama",
  "RIANTI_HIDAYAT": "Rianti Hidayat",
  "ROND": "Rond",
  "RYO_UEDA": "Ryo Ueda",
  "RYOTA_MURAYAMA": "Ryota Murayama",
  "RYTA_FUSE": "Ryta Fuse",
  "RYUTA_FUSE": "Ryuta Fuse",
  "SATOSHI_NAKAI": "SATOSHI NAKAI",
  "SIE_NANAHARA": "SIE NANAHARA",
  "SABOTERI": "Saboteri",
  "SACHIKO_ADACHI": "Sachiko Adachi",
  "SAKI_HAYASHIRO": "Saki Hayashiro",
  "SAKIKO_MAEDA": "Sakiko Maeda",
  "SANOSUKE_SAKUMA": "Sanosuke Sakuma",
  "SATOSHI_ITO": "Satoshi Ito",
  "SATOSHI_SHIRAI": "Satoshi Shirai",
  "SAYA_TSURUTA": "Saya Tsuruta",
  "SCAV": "Scav",
  "SEKIO": "Sekio",
  "SHIBURINGARU": "Shiburingaru",
  "SHIBUZOH": "Shibuzoh.",
  "SHIGENORI_NEGISHI": "Shigenori Negishi",
  "SHIMARIS_YUKICHI": "Shimaris Yukichi",
  "SHIN_NAGASAWA": "Shin Nagasawa",
  "SHIN_ICHI_YOSHIDA": "Shin-ichi Yoshida",
  "SHINJI_KANDA": "Shinji Kanda",
  "SHINYA_KOMATSU": "Shinya Komatsu",
  "SHINYA_MIZUNO": "Shinya Mizuno",
  "SONOSUKE_SKAUMA": "Sonosuke Skauma",
  "SOUICHIROU_GUNJIMA": "Souichirou Gunjima",
  "SPIKE_CHUNSOFT": "Spike Chunsoft.",
  "STUDIO_BORA_INC": "Studio Bora Inc.",
  "SUMIYOSHI_KIZUKI": "Sumiyoshi Kizuki",
  "SUSUMU_MAEYA": "Susumu Maeya",
  "SUWAMA_CHIAKI": "Suwama Chiaki",
  "TOKIYA": "TOKIYA",
  "TOMATO_MARKET": "TOMATO MARKET",
  "TAIGA_KASAI": "Taiga Kasai",
  "TAIGA_KAYAMA": "Taiga Kayama",
  "TAIRA_AKITSU": "Taira Akitsu",
  "TAKESHI_NAKAMURA": "Takeshi Nakamura",
  "TAKUMI_WADA": "Takumi Wada",
  "TEEZIRO": "Teeziro",
  "TERADA_TERA": "Terada Tera",
  "TETSU_KAYAMA": "Tetsu Kayama",
  "TETSUO_HARA": "Tetsuo Hara",
  "TETSUO_YAJIMA": "Tetsuo Yajima",
  "TIKA_MATSUNO": "Tika Matsuno",
  "TOMOAKI_IMAKUNI": "Tomoaki Imakuni",
  "TOMOKAZU_KOMIYA": "Tomokazu Komiya",
  "TOMOKI_SONE": "Tomoki Sone",
  "TOMOMI_KANEKO": "Tomomi Kaneko",
  "TOMOMI_OZAKI": "Tomomi Ozaki",
  "TOMOWAKA": "Tomowaka",
  "TONJI_MATSUNO": "Tonji Matsuno",
  "TOSHINAO_AOKI": "Toshinao Aoki",
  "TOYSTE_BEACH": "Toyste Beach",
  "TSUYOSHI_NAGANO": "Tsuyoshi Nagano",
  "UKUMO_UITI": "UKUMO uiti",
  "USGMEN": "USGMEN",
  "ULTIMATEINUDOG": "Ultimateinudog",
  "UNINORI": "Uninori",
  "UTA": "Uta",
  "WHISKER": "Whisker",
  "WINTR_WANDR": "Wintr Wandr",
  "YASHIRO_NANACO": "YASHIRO Nanaco",
  "YU_NAGABA": "YU NAGABA",
  "YANO_KEIJI": "Yano Keiji",
  "YOKO_HISHIDA": "Yoko Hishida",
  "YORIYUKI_IKEGAMI": "Yoriyuki Ikegami",
  "YOSHIMI_MIYOSHI": "Yoshimi Miyoshi",
  "YOSHIMOTO_YOSHIMON": "Yoshimoto Yoshimon",
  "YOSHINOBU_SAITO": "Yoshinobu Saito",
  "YOSHIOKA": "Yoshioka",
  "YOU_IRIBI": "You Iribi",
  "YUKA_MORII": "Yuka Morii",
  "YUKA_TANAKA": "Yuka Tanaka",
  "YUKIHIRO_TADA": "Yukihiro Tada",
  "YUKIKO_BABA": "Yukiko Baba",
  "YUMI": "Yumi",
  "YURIKO_AKASE": "Yuriko Akase",
  "YUSUKE_KOZAKI": "Yusuke Kozaki",
  "YUSUKE_OHMURA": "Yusuke Ohmura",
  "YUTA_KAWAZU": "Yuta Kawazu",
  "YUU_NISHIDA": "Yuu Nishida",
  "YUYA_OKA": "Yuya Oka",
  "ZU_KA": "Zu-Ka",
  "AKAGI": "akagi",
  "AKY_CG_WORKS": "aky CG Works",
  "AOKI": "aoki",
  "ASPARA": "aspara",
  "BOOOTA": "booota",
  "BUCHI": "buchi",
  "BURARI": "burari",
  "CHIBI": "chibi",
  "COCHI8I": "cochi8i",
  "DANCIAO": "danciao",
  "HANABUSHI": "hanabushi",
  "HATACHU": "hatachu",
  "HNCL": "hncl",
  "IMONIII": "imoniii",
  "KAMONABE": "kamonabe",
  "KANAHEI": "kanahei",
  "KANTARO": "kantaro",
  "KAWAYOO": "kawayoo",
  "KIRISAKI": "kirisAki",
  "KODAMA": "kodama",
  "KURUMITSU": "kurumitsu",
  "MASHU": "mashu",
  "MATAZO": "matazo",
  "MATCH": "match",
  "MELE": "mele",
  "MIKI_KUDO": "miki kudo",
  "MINGO": "mingo",
  "NAGANO": "nagano",
  "NAGIMISO": "nagimiso",
  "NISIMONO": "nisimono",
  "OKAYAMATAKATOSHI": "okayamatakatoshi",
  "OSARE": "osare",
  "OTUMAMI": "otumami",
  "RIKA": "rika",
  "RYOMA_URATSUKA": "ryoma uratsuka",
  "SADAJI": "sadaji",
  "SAINO_MISAKI": "saino misaki",
  "SATOMA": "satoma",
  "SO_TARO": "so-taro",
  "SOWSOW": "sowsow",
  "SUI": "sui",
  "SVLT": "svlt",
  "TAKASHI_SHIRAISHI": "takashi shiraishi",
  "TAKE": "take",
  "TAKUYOA": "takuyoa",
  "TAYU": "tayu",
  "TETSUYA_KOIZUMI": "tetsuya koizumi",
  "TOI8": "toi8",
  "TONO": "tono",
  "TORIYUFU": "toriyufu",
  "YUU": "yuu",
  "ZIG": "zig"
} as const;

export const CARD_VARIANT_TYPES = {
  "HOLO": "holo",
  "NORMAL": "normal",
  "REVERSE": "reverse"
} as const;

export const CARD_VARIANT_SUB_TYPES = {
  "1995_1998_COPYRIGHT": "1995-1998-copyright",
  "2019_COPYRIGHT": "2019-copyright",
  "2020_COPYRIGHT": "2020-copyright",
  "NINTEDO_ERROR": "nintedo-error",
  "NO_RARITY": "no-rarity",
  "UNLIMITED": "unlimited"
} as const;

export const CARD_VARIANT_STAMPS = {
  "1ST_EDITION": [
    "1st Edition",
    "1st edition",
    "1st-edition"
  ]
} as const;

export const CARD_RARITIES = {
  "ACE_SPEC_RARE": "ACE SPEC Rare",
  "BLACK_WHITE_RARE": "Black White Rare",
  "CHARACTER_RARE": "Character Rare",
  "CHARACTER_SUPER_RARE": "Character Super Rare",
  "COMMON": "Common",
  "DOUBLE_RARE": "Double rare",
  "HOLO_RARE": "Holo Rare",
  "HYPER_RARE": "Hyper rare",
  "ILLUSTRATION_RARE": "Illustration rare",
  "MEGA_HYPER_RARE": "Mega Hyper Rare",
  "NONE": "None",
  "PROMO": "Promo",
  "RADIANT_RARE": "Radiant Rare",
  "RARE": "Rare",
  "RARE_HOLO": "Rare Holo",
  "SECRET_RARE": "Secret Rare",
  "SHINY_ULTRA_RARE": "Shiny Ultra Rare",
  "SHINY_RARE": "Shiny rare",
  "SPECIAL_ILLUSTRATION_RARE": "Special illustration rare",
  "TRIPLE_RARE": "Triple Rare",
  "ULTRA_RARE": "Ultra Rare",
  "UNCOMMON": "Uncommon"
} as const;

export const CARD_CATEGORIES = {
  "ENERGY": "Energy",
  "POKEMON": "Pokemon",
  "TRAINER": "Trainer"
} as const;

export const CARD_REGULATION_MARKS = {
  "A": "A",
  "B": "B",
  "C": "C",
  "D": "D",
  "E": "E",
  "F": "F",
  "G": "G",
  "H": "H",
  "I": "I",
  "J": "J"
} as const;

export const TCG_PLAYER_GROUPS = {} as const;

