export const COMMIT = 'd86b5107d09484994f7fa15c45b0af8ffd72e1b0';

export const VERSION = 'master';

export const SERIES = {
  BASE: 'base',
  BLACK_AND_WHITE: 'bw',
  CALL_OF_LEGENDS: 'col',
  DIAMOND_AND_PEARL: 'dp',
  EX: 'ex',
  E_CARD: 'ecard',
  GYM: 'gym',
  HEARTGOLD_AND_SOULSILVER: 'hgss',
  LEGENDARY_COLLECTION: 'lc',
  MCDONALDS_COLLECTION: 'mc',
  MEGA_EVOLUTION: 'me',
  MISCELLANEOUS: 'misc',
  NEO: 'neo',
  PLATINUM: 'pl',
  POKEMON_TCG_POCKET: 'tcgp',
  POP: 'pop',
  SCARLET_AND_VIOLET: 'sv',
  SUN_AND_MOON: 'sm',
  SWORD_AND_SHIELD: 'swsh',
  TRAINER_KITS: 'tk',
  XY: 'xy',
} as const;

export const SERIES_IDS = [
  'base',
  'bw',
  'col',
  'dp',
  'ecard',
  'ex',
  'gym',
  'hgss',
  'lc',
  'mc',
  'me',
  'misc',
  'neo',
  'pl',
  'pop',
  'sm',
  'sv',
  'swsh',
  'tcgp',
  'tk',
  'xy',
] as const;

export const SETS = {
  BASE: {
    BASE_SET: 'base1',
    BASE_SET_2: 'base4',
    FOSSIL: 'base3',
    JUNGLE: 'base2',
    TEAM_ROCKET: 'base5',
    WIZARDS_BLACK_STAR_PROMOS: 'basep',
  },
  BLACK_AND_WHITE: {
    BLACK_AND_WHITE: 'bw1',
    BOUNDARIES_CROSSED: 'bw7',
    BW_BLACK_STAR_PROMOS: 'bwp',
    DARK_EXPLORERS: 'bw5',
    DRAGONS_EXALTED: 'bw6',
    DRAGON_VAULT: 'dv1',
    EMERGING_POWERS: 'bw2',
    LEGENDARY_TREASURES: 'bw11',
    NEXT_DESTINIES: 'bw4',
    NOBLE_VICTORIES: 'bw3',
    PLASMA_BLAST: 'bw10',
    PLASMA_FREEZE: 'bw9',
    PLASMA_STORM: 'bw8',
  },
  CALL_OF_LEGENDS: {
    CALL_OF_LEGENDS: 'col1',
  },
  DIAMOND_AND_PEARL: {
    DIAMOND_AND_PEARL: 'dp1',
    DP_BLACK_STAR_PROMOS: 'dpp',
    GREAT_ENCOUNTERS: 'dp4',
    LEGENDS_AWAKENED: 'dp6',
    MAJESTIC_DAWN: 'dp5',
    MYSTERIOUS_TREASURES: 'dp2',
    SECRET_WONDERS: 'dp3',
    STORMFRONT: 'dp7',
  },
  EX: {
    CRYSTAL_GUARDIANS: 'ex14',
    DELTA_SPECIES: 'ex11',
    DEOXYS: 'ex8',
    DRAGON: 'ex3',
    DRAGON_FRONTIERS: 'ex15',
    EMERALD: 'ex9',
    FIRERED_AND_LEAFGREEN: 'ex6',
    HIDDEN_LEGENDS: 'ex5',
    HOLON_PHANTOMS: 'ex13',
    LEGEND_MAKER: 'ex12',
    POKE_CARD_CREATOR_PACK: 'ex5.5',
    POWER_KEEPERS: 'ex16',
    RUBY_AND_SAPPHIRE: 'ex1',
    SANDSTORM: 'ex2',
    TEAM_MAGMA_VS_TEAM_AQUA: 'ex4',
    TEAM_ROCKET_RETURNS: 'ex7',
    UNSEEN_FORCES: 'ex10',
    UNSEEN_FORCES_UNOWN_COLLECTION: 'exu',
  },
  E_CARD: {
    AQUAPOLIS: 'ecard2',
    BEST_OF_GAME: 'bog',
    EXPEDITION_BASE_SET: 'ecard1',
    SKYRIDGE: 'ecard3',
  },
  GYM: {
    GYM_CHALLENGE: 'gym2',
    GYM_HEROES: 'gym1',
  },
  HEARTGOLD_AND_SOULSILVER: {
    HEARTGOLD_SOULSILVER: 'hgss1',
    HGSS_BLACK_STAR_PROMOS: 'hgssp',
    TRIUMPHANT: 'hgss4',
    UNDAUNTED: 'hgss3',
    UNLEASHED: 'hgss2',
  },
  LEGENDARY_COLLECTION: {
    LEGENDARY_COLLECTION: 'lc',
  },
  MCDONALDS_COLLECTION: {
    '2013BW': '2013bw',
    '2018SM_FR': '2018sm-fr',
    '2019SM_FR': '2019sm-fr',
    MCDONALDS_COLLECTION_2011: '2011bw',
    MCDONALDS_COLLECTION_2012: '2012bw',
    MCDONALDS_COLLECTION_2014: '2014xy',
    MCDONALDS_COLLECTION_2015: '2015xy',
    MCDONALDS_COLLECTION_2016: '2016xy',
    MCDONALDS_COLLECTION_2017: '2017sm',
    MCDONALDS_COLLECTION_2018: '2018sm',
    MCDONALDS_COLLECTION_2019: '2019sm',
    MCDONALDS_COLLECTION_2021: '2021swsh',
    MCDONALDS_COLLECTION_2022: '2022swsh',
    MCDONALDS_COLLECTION_2023: '2023sv',
    MCDONALDS_COLLECTION_2024: '2024sv',
  },
  MEGA_EVOLUTION: {
    ASCENDED_HEROES: 'me02.5',
    CHAOS_RISING: 'me04',
    MEGA_EVOLUTION: 'me01',
    MEGA_EVOLUTION_ENERGY: 'mee',
    MEP_BLACK_STAR_PROMOS: 'mep',
    PERFECT_ORDER: 'me03',
    PHANTASMAL_FLAMES: 'me02',
    PITCH_BLACK: 'me05',
  },
  MISCELLANEOUS: {
    MISCELLANEOUS_PROMOS: 'miscp',
  },
  NEO: {
    NEO_DESTINY: 'neo4',
    NEO_DISCOVERY: 'neo2',
    NEO_GENESIS: 'neo1',
    NEO_REVELATION: 'neo3',
    SOUTHERN_ISLANDS: 'si1',
  },
  PLATINUM: {
    ARCEUS: 'pl4',
    PLATINUM: 'pl1',
    POKEMON_RUMBLE: 'ru1',
    RISING_RIVALS: 'pl2',
    SUPREME_VICTORS: 'pl3',
  },
  POKEMON_TCG_POCKET: {
    CELESTIAL_GUARDIANS: 'A3',
    CRIMSON_BLAZE: 'B1a',
    EEVEE_GROVE: 'A3b',
    EXTRADIMENSIONAL_CRISIS: 'A3a',
    FANTASTICAL_PARADE: 'B2',
    GENETIC_APEX: 'A1',
    MEGA_RISING: 'B1',
    MYTHICAL_ISLAND: 'A1a',
    PALDEAN_WONDERS: 'B2a',
    PROMOS_A: 'P-A',
    SECLUDED_SPRINGS: 'A4a',
    SHINING_REVELRY: 'A2b',
    SPACE_TIME_SMACKDOWN: 'A2',
    TRIUMPHANT_LIGHT: 'A2a',
    WISDOM_OF_SEA_AND_SKY: 'A4',
  },
  POP: {
    NINTENDO_BLACK_STAR_PROMOS: 'np',
    POP_SERIES_1: 'pop1',
    POP_SERIES_2: 'pop2',
    POP_SERIES_3: 'pop3',
    POP_SERIES_4: 'pop4',
    POP_SERIES_5: 'pop5',
    POP_SERIES_6: 'pop6',
    POP_SERIES_7: 'pop7',
    POP_SERIES_8: 'pop8',
    POP_SERIES_9: 'pop9',
  },
  SCARLET_AND_VIOLET: {
    '151': 'sv03.5',
    BLACK_BOLT: 'sv10.5b',
    DESTINED_RIVALS: 'sv10',
    JOURNEY_TOGETHER: 'sv09',
    MY_FIRST_BATTLE: 'mfb',
    OBSIDIAN_FLAMES: 'sv03',
    PALDEAN_FATES: 'sv04.5',
    PALDEA_EVOLVED: 'sv02',
    PARADOX_RIFT: 'sv04',
    PRISMATIC_EVOLUTIONS: 'sv08.5',
    SCARLET_AND_VIOLET: 'sv01',
    SCARLET_AND_VIOLET_ENERGY: 'sve',
    SHROUDED_FABLE: 'sv06.5',
    STELLAR_CROWN: 'sv07',
    SURGING_SPARKS: 'sv08',
    SVP_BLACK_STAR_PROMOS: 'svp',
    TEMPORAL_FORCES: 'sv05',
    TWILIGHT_MASQUERADE: 'sv06',
    WHITE_FLARE: 'sv10.5w',
  },
  SUN_AND_MOON: {
    BURNING_SHADOWS: 'sm3',
    CELESTIAL_STORM: 'sm7',
    COSMIC_ECLIPSE: 'sm12',
    CRIMSON_INVASION: 'sm4',
    DETECTIVE_PIKACHU: 'det1',
    DRAGON_MAJESTY: 'sm7.5',
    FORBIDDEN_LIGHT: 'sm6',
    GUARDIANS_RISING: 'sm2',
    HIDDEN_FATES: 'sm115',
    HIDDEN_FATES_SHINY_VAULT: 'sma',
    LOST_THUNDER: 'sm8',
    SHINING_LEGENDS: 'sm3.5',
    SM_BLACK_STAR_PROMOS: 'smp',
    SUN_AND_MOON: 'sm1',
    TEAM_UP: 'sm9',
    ULTRA_PRISM: 'sm5',
    UNBROKEN_BONDS: 'sm10',
    UNIFIED_MINDS: 'sm11',
  },
  SWORD_AND_SHIELD: {
    ASTRAL_RADIANCE: 'swsh10',
    ASTRAL_RADIANCE_TRAINER_GALLERY: 'swsh10tg',
    BATTLE_STYLES: 'swsh5',
    BRILLIANT_STARS: 'swsh9',
    BRILLIANT_STARS_TRAINER_GALLERY: 'swsh9tg',
    CELEBRATIONS: 'cel25',
    CELEBRATIONS_CLASSIC_COLLECTION: 'cel25cc',
    CHAMPIONS_PATH: 'swsh3.5',
    CHILLING_REIGN: 'swsh6',
    CROWN_ZENITH: 'swsh12.5',
    CROWN_ZENITH_GALARIAN_GALLERY: 'swsh12.5gg',
    DARKNESS_ABLAZE: 'swsh3',
    EVOLVING_SKIES: 'swsh7',
    FUSION_STRIKE: 'swsh8',
    LOST_ORIGIN: 'swsh11',
    LOST_ORIGIN_TRAINER_GALLERY: 'swsh11tg',
    POKEMON_FUTSAL_2020: 'fut2020',
    POKEMON_GO: 'swsh10.5',
    REBEL_CLASH: 'swsh2',
    SHINING_FATES: 'swsh4.5',
    SHINING_FATES_SHINY_VAULT: 'swsh4.5sv',
    SILVER_TEMPEST: 'swsh12',
    SILVER_TEMPEST_TRAINER_GALLERY: 'swsh12tg',
    SWORD_AND_SHIELD: 'swsh1',
    SWSH_BLACK_STAR_PROMOS: 'swshp',
    VIVID_VOLTAGE: 'swsh4',
  },
  TRAINER_KITS: {
    BW_TRAINER_KIT_EXCADRILL: 'tk-bw-e',
    BW_TRAINER_KIT_ZOROARK: 'tk-bw-z',
    DP_TRAINER_KIT_LUCARIO: 'tk-dp-l',
    DP_TRAINER_KIT_MANAPHY: 'tk-dp-m',
    EX_TRAINER_KIT_2_MINUN: 'tk-ex-m',
    EX_TRAINER_KIT_2_PLUSLE: 'tk-ex-p',
    EX_TRAINER_KIT_LATIAS: 'tk-ex-latia',
    EX_TRAINER_KIT_LATIOS: 'tk-ex-latio',
    HS_TRAINER_KIT_GYARADOS: 'tk-hs-g',
    HS_TRAINER_KIT_RAICHU: 'tk-hs-r',
    SM_TRAINER_KIT_ALOLAN_RAICHU: 'tk-sm-r',
    SM_TRAINER_KIT_LYCANROC: 'tk-sm-l',
    XY_TRAINER_KIT_BISHARP: 'tk-xy-b',
    XY_TRAINER_KIT_LATIAS: 'tk-xy-latia',
    XY_TRAINER_KIT_LATIOS: 'tk-xy-latio',
    XY_TRAINER_KIT_NOIVERN: 'tk-xy-n',
    XY_TRAINER_KIT_PIKACHU_LIBRE: 'tk-xy-p',
    XY_TRAINER_KIT_SUICUNE: 'tk-xy-su',
    XY_TRAINER_KIT_SYLVEON: 'tk-xy-sy',
    XY_TRAINER_KIT_WIGGLYTUFF: 'tk-xy-w',
  },
  XY: {
    ANCIENT_ORIGINS: 'xy7',
    BREAKPOINT: 'xy9',
    BREAKTHROUGH: 'xy8',
    DOUBLE_CRISIS: 'dc1',
    EVOLUTIONS: 'xy12',
    FATES_COLLIDE: 'xy10',
    FLASHFIRE: 'xy2',
    FURIOUS_FISTS: 'xy3',
    GENERATIONS: 'g1',
    KALOS_STARTER_SET: 'xy0',
    PHANTOM_FORCES: 'xy4',
    PRIMAL_CLASH: 'xy5',
    ROARING_SKIES: 'xy6',
    STEAM_SIEGE: 'xy11',
    XY: 'xy1',
    XY_BLACK_STAR_PROMOS: 'xyp',
    YELLOW_A_ALTERNATE: 'xya',
  },
} as const;

export const SET_IDS = [
  '2011bw',
  '2012bw',
  '2013bw',
  '2014xy',
  '2015xy',
  '2016xy',
  '2017sm',
  '2018sm',
  '2018sm-fr',
  '2019sm',
  '2019sm-fr',
  '2021swsh',
  '2022swsh',
  '2023sv',
  '2024sv',
  'A1',
  'A1a',
  'A2',
  'A2a',
  'A2b',
  'A3',
  'A3a',
  'A3b',
  'A4',
  'A4a',
  'B1',
  'B1a',
  'B2',
  'B2a',
  'P-A',
  'base1',
  'base2',
  'base3',
  'base4',
  'base5',
  'basep',
  'bog',
  'bw1',
  'bw10',
  'bw11',
  'bw2',
  'bw3',
  'bw4',
  'bw5',
  'bw6',
  'bw7',
  'bw8',
  'bw9',
  'bwp',
  'cel25',
  'cel25cc',
  'col1',
  'dc1',
  'det1',
  'dp1',
  'dp2',
  'dp3',
  'dp4',
  'dp5',
  'dp6',
  'dp7',
  'dpp',
  'dv1',
  'ecard1',
  'ecard2',
  'ecard3',
  'ex1',
  'ex10',
  'ex11',
  'ex12',
  'ex13',
  'ex14',
  'ex15',
  'ex16',
  'ex2',
  'ex3',
  'ex4',
  'ex5',
  'ex5.5',
  'ex6',
  'ex7',
  'ex8',
  'ex9',
  'exu',
  'fut2020',
  'g1',
  'gym1',
  'gym2',
  'hgss1',
  'hgss2',
  'hgss3',
  'hgss4',
  'hgssp',
  'lc',
  'me01',
  'me02',
  'me02.5',
  'me03',
  'me04',
  'me05',
  'mee',
  'mep',
  'mfb',
  'miscp',
  'neo1',
  'neo2',
  'neo3',
  'neo4',
  'np',
  'pl1',
  'pl2',
  'pl3',
  'pl4',
  'pop1',
  'pop2',
  'pop3',
  'pop4',
  'pop5',
  'pop6',
  'pop7',
  'pop8',
  'pop9',
  'ru1',
  'si1',
  'sm1',
  'sm10',
  'sm11',
  'sm115',
  'sm12',
  'sm2',
  'sm3',
  'sm3.5',
  'sm4',
  'sm5',
  'sm6',
  'sm7',
  'sm7.5',
  'sm8',
  'sm9',
  'sma',
  'smp',
  'sv01',
  'sv02',
  'sv03',
  'sv03.5',
  'sv04',
  'sv04.5',
  'sv05',
  'sv06',
  'sv06.5',
  'sv07',
  'sv08',
  'sv08.5',
  'sv09',
  'sv10',
  'sv10.5b',
  'sv10.5w',
  'sve',
  'svp',
  'swsh1',
  'swsh10',
  'swsh10.5',
  'swsh10tg',
  'swsh11',
  'swsh11tg',
  'swsh12',
  'swsh12.5',
  'swsh12.5gg',
  'swsh12tg',
  'swsh2',
  'swsh3',
  'swsh3.5',
  'swsh4',
  'swsh4.5',
  'swsh4.5sv',
  'swsh5',
  'swsh6',
  'swsh7',
  'swsh8',
  'swsh9',
  'swsh9tg',
  'swshp',
  'tk-bw-e',
  'tk-bw-z',
  'tk-dp-l',
  'tk-dp-m',
  'tk-ex-latia',
  'tk-ex-latio',
  'tk-ex-m',
  'tk-ex-p',
  'tk-hs-g',
  'tk-hs-r',
  'tk-sm-l',
  'tk-sm-r',
  'tk-xy-b',
  'tk-xy-latia',
  'tk-xy-latio',
  'tk-xy-n',
  'tk-xy-p',
  'tk-xy-su',
  'tk-xy-sy',
  'tk-xy-w',
  'xy0',
  'xy1',
  'xy10',
  'xy11',
  'xy12',
  'xy2',
  'xy3',
  'xy4',
  'xy5',
  'xy6',
  'xy7',
  'xy8',
  'xy9',
  'xya',
  'xyp',
] as const;

export const SET_IDS_BY_SERIES_ID = {
  base: ['basep', 'base5', 'base2', 'base3', 'base1', 'base4'],
  bw: ['bw8', 'bw9', 'bw10', 'bw3', 'bw4', 'bw11', 'bw2', 'bw6', 'dv1', 'bw5', 'bw7', 'bw1', 'bwp'],
  col: ['col1'],
  dp: ['dp7', 'dp3', 'dp2', 'dp5', 'dp6', 'dp4', 'dp1', 'dpp'],
  ecard: ['ecard3', 'ecard1', 'bog', 'ecard2'],
  ex: [
    'ex10',
    'exu',
    'ex7',
    'ex4',
    'ex2',
    'ex1',
    'ex16',
    'ex5.5',
    'ex12',
    'ex13',
    'ex5',
    'ex6',
    'ex9',
    'ex3',
    'ex15',
    'ex8',
    'ex11',
    'ex14',
  ],
  gym: ['gym1', 'gym2'],
  hgss: ['hgss2', 'hgss3', 'hgss4', 'hgss1', 'hgssp'],
  lc: ['lc'],
  mc: [
    '2024sv',
    '2023sv',
    '2022swsh',
    '2021swsh',
    '2019sm',
    '2018sm',
    '2017sm',
    '2016xy',
    '2015xy',
    '2014xy',
    '2012bw',
    '2011bw',
    '2019sm-fr',
    '2018sm-fr',
    '2013bw',
  ],
  me: ['me05', 'me02', 'me03', 'me01', 'mee', 'mep', 'me04', 'me02.5'],
  misc: ['miscp'],
  neo: ['si1', 'neo3', 'neo1', 'neo2', 'neo4'],
  pl: ['pl3', 'pl2', 'ru1', 'pl1', 'pl4'],
  pop: ['pop9', 'pop8', 'pop7', 'pop6', 'pop5', 'pop4', 'pop3', 'pop2', 'pop1', 'np'],
  sm: [
    'sm11',
    'sm10',
    'sm5',
    'sm9',
    'sm1',
    'sm3.5',
    'smp',
    'sm8',
    'sm115',
    'sma',
    'sm2',
    'sm6',
    'sm7.5',
    'det1',
    'sm4',
    'sm12',
    'sm7',
    'sm3',
  ],
  sv: [
    'sv03.5',
    'sv10.5w',
    'sv06',
    'sv05',
    'sv08',
    'sv07',
    'sv06.5',
    'sv01',
    'sve',
    'svp',
    'sv08.5',
    'sv04',
    'sv04.5',
    'sv02',
    'sv03',
    'mfb',
    'sv09',
    'sv10',
    'sv10.5b',
  ],
  swsh: [
    'swsh4',
    'swsh1',
    'swsh12',
    'swsh12tg',
    'swsh4.5',
    'swsh4.5sv',
    'swshp',
    'swsh2',
    'swsh10.5',
    'fut2020',
    'swsh11',
    'swsh11tg',
    'swsh8',
    'swsh7',
    'swsh3',
    'swsh12.5',
    'swsh12.5gg',
    'swsh6',
    'swsh3.5',
    'cel25',
    'cel25cc',
    'swsh9',
    'swsh9tg',
    'swsh5',
    'swsh10',
    'swsh10tg',
  ],
  tcgp: [
    'A4',
    'A2a',
    'A2',
    'A2b',
    'A4a',
    'P-A',
    'B2a',
    'A1a',
    'B1',
    'A1',
    'B2',
    'A3a',
    'A3b',
    'B1a',
    'A3',
  ],
  tk: [
    'tk-xy-w',
    'tk-xy-sy',
    'tk-xy-su',
    'tk-xy-p',
    'tk-xy-n',
    'tk-xy-latio',
    'tk-xy-latia',
    'tk-xy-b',
    'tk-sm-l',
    'tk-sm-r',
    'tk-hs-r',
    'tk-hs-g',
    'tk-ex-p',
    'tk-ex-m',
    'tk-ex-latio',
    'tk-ex-latia',
    'tk-dp-m',
    'tk-dp-l',
    'tk-bw-z',
    'tk-bw-e',
  ],
  xy: [
    'xya',
    'xy1',
    'xyp',
    'xy11',
    'xy6',
    'xy5',
    'xy4',
    'xy0',
    'g1',
    'xy3',
    'xy2',
    'xy10',
    'xy12',
    'dc1',
    'xy8',
    'xy9',
    'xy7',
  ],
} as const;

export const CARD_ILLUSTRATORS = {
  BIG_MAMA_TAGAWA: ['"Big Mama" Tagawa', '"Big Mama" Tagawa"'],
  BIG_MAMA_TAGAWABIG_MAMA_TAGAWA: '"Big Mama" Tagawa"Big Mama" Tagawa',
  '0313': '0313',
  '2017_PIKACHU_PROJECT': '2017 Pikachu Project',
  '2019_PIKACHU_PROJECT': '2019 Pikachu Project',
  '5BAN_GRAPHICS': '5ban Graphics',
  AKIRA_EGAWA: 'AKIRA EGAWA',
  AYUMI_ODASHIMA: 'AYUMI ODASHIMA',
  ACORVIART: 'Acorviart',
  AIMI_TOMITA: 'Aimi Tomita',
  AKINO_FUKUJI: 'Akino Fukuji',
  AKIRA_KOMAYAMA: 'Akira Komayama',
  ALIYA_CHEN: 'Aliya Chen',
  AMELICART: 'Amelicart',
  ANDERSON: 'Anderson',
  ANESAKI_DYNAMIC: 'Anesaki Dynamic',
  APIOS: 'Apios',
  ARAI_KIRIKO: 'Arai Kiriko',
  ASAKO_ITO: 'Asako Ito',
  ASUKA_IWASHITA: 'Asuka Iwashita',
  ATSUKO_NISHIDA: 'Atsuko Nishida',
  ATSUKO_UJIIE: 'Atsuko Ujiie',
  ATSUSHI_FURUSAWA: 'Atsushi Furusawa',
  ATSUYA_UKI: 'Atsuya Uki',
  AVEC_YOKO: 'Avec Yoko',
  AYA_KUSUBE: 'Aya Kusube',
  AYAKA_YOSHIDA: 'Ayaka Yoshida',
  AYAKO_OZAKI: 'Ayako Ozaki',
  AYOKO_YOSHIDA: 'Ayoko Yoshida',
  BERUBURI: 'BERUBURI',
  BENIMARU_ITOH: 'Benimaru Itoh',
  BUN_TOUJO: 'Bun Toujo',
  CHORISO: 'CHORISO',
  CR_CG_GANGS: 'CR CG gangs',
  CHRISTOPHER_RUSH: 'Christopher Rush',
  CONA_NITANDA: 'Cona Nitanda',
  CONCEPTLAB: 'ConceptLab',
  CRAIG_TURVEY: 'Craig Turvey',
  DAG_INC: 'D.A.G Inc.',
  DOM: 'DOM',
  DAISUKE_ITO: 'Daisuke Ito',
  DAISUKE_IWAMOTO: 'Daisuke Iwamoto',
  DEMIZUPOSUKA: 'DemizuPosuka',
  DROOYAMA: 'Dr.Ooyama',
  DSUKE: 'Dsuke',
  EBILA: 'Ebila',
  EMI_ANDO: 'Emi Ando',
  EMI_MIWA: 'Emi Miwa',
  EMI_YOSHIDA: 'Emi Yoshida',
  EN_MORIKURA: 'En Morikura',
  ERI_KAMEI: 'Eri Kamei',
  ERI_YAMAKI: 'Eri Yamaki',
  ESKE_YOSHINOB: 'Eske Yoshinob',
  ETSUYA_HATTORI: 'Etsuya Hattori',
  FELICIA_CHEN: 'Felicia Chen',
  FRAMESTORE: 'Framestore',
  FUJIMOTO_GOLD: 'Fujimoto Gold',
  FUMIE_KITTAKA: 'Fumie Kittaka',
  GAME_FREAK_INC: 'GAME FREAK inc.',
  GIDORA: 'GIDORA',
  GOSSAN: 'GOSSAN',
  GOTO_MINORI: 'GOTO minori',
  GAKUJI_NOMOTO: 'Gakuji Nomoto',
  GAPAO: 'Gapao',
  GEMI: 'Gemi',
  HACCAN: 'HACCAN',
  HAGIYA_KAORU: 'HAGIYA Kaoru',
  HICO_KIM: 'HICO KIM',
  HYOGONOSUKE: 'HYOGONOSUKE',
  HAJIME_KUSAJIMA: 'Hajime Kusajima',
  HARU_AKASAKA: 'Haru Akasaka',
  HARUKO_ICHIKAWA: 'Haruko Ichikawa',
  HASEGAWA_SAKI: 'Hasegawa Saki',
  HASUNO: 'Hasuno',
  HATAYA: 'Hataya',
  HEISUKE_KITAZAWA: 'Heisuke Kitazawa',
  HIRON: 'HiRON',
  HIDEAKI_HAKOZAKI: 'Hideaki Hakozaki',
  HIDEKI_ISHIKAWA: 'Hideki Ishikawa',
  HIDEKI_KAZAMA: 'Hideki Kazama',
  HIDEYUKI_NAKAJIMA: 'Hideyuki Nakajima',
  HIKARU_KOIKE: 'Hikaru Koike',
  HIROAKI_ITO: 'Hiroaki Ito',
  HIROKI_ASANUMA: 'Hiroki Asanuma',
  HIROKI_FUCHINO: 'Hiroki Fuchino',
  HIROMICHI_SUGIYAMA: 'Hiromichi Sugiyama',
  HIRONOBU_YOSHIDA: 'Hironobu Yoshida',
  HIROYUKI_YAMAMOTO: 'Hiroyuki Yamamoto',
  HISAO_NAKAMURA: 'Hisao Nakamura',
  HITOSHI_ARIGA: 'Hitoshi Ariga',
  HIZUKI_MISONO: 'Hizuki Misono',
  HOSHINO_KURO: 'Hoshino KURO',
  HUANG_TZU_EN: 'Huang Tzu En',
  IKEDA_SAKI: 'IKEDA Saki',
  ILLUS_AND_DIREC_THE_POKEMON_COMPANY_ART_TEAM: 'Illus. & Direc. The Pokémon Company Art Team',
  IMAKUNI: 'Imakuni?',
  IORI_SUZUKI: 'Iori Suzuki',
  ITO_KYOKO: 'Ito Kyoko',
  IWAMOTO05: 'Iwamoto05',
  IZUCCH: 'Izucch',
  JAMES_TURNER: 'James Turner',
  JERKY: 'Jerky',
  JIRO_SASUMO: 'Jiro Sasumo',
  JULIE_HANG: 'Julie Hang',
  JUMPEI_AKASAKA: 'Jumpei Akasaka',
  JUNE: 'June',
  JUNGO_SUZUKI: 'Jungo Suzuki',
  JUNSEI_KUNINOBU: 'Junsei Kuninobu',
  K_HOSHIBA: 'K. Hoshiba',
  K_UTSUNOMIYA: 'K. Utsunomiya',
  KEIICHIRO_ITO: 'KEIICHIRO ITO',
  KG_2000: 'KG-2000',
  KIYOTAKA_OSHIYAMA: 'KIYOTAKA OSHIYAMA',
  KYUPIYAMA: 'KYUPIYAMA',
  KAGEMARU_HIMENO: 'Kagemaru Himeno',
  KAI_ISHIKAWA: 'Kai Ishikawa',
  KAMOME_SHIRAHAMA: 'Kamome Shirahama',
  KANAKO_EO: 'Kanako Eo',
  KANAMI_OGATA: 'Kanami Ogata',
  KANNNU: 'Kannnu',
  KARIYA: 'Kariya',
  KATIE_GROSS: 'Katie Gross',
  KATSUNORI_SATO: 'Katsunori Sato',
  KATSURA_TABATA: 'Katsura Tabata',
  KAZUAKI_AIHARA: 'Kazuaki Aihara',
  KAZUHISA_URAGAMI: 'Kazuhisa Uragami',
  KAZUKI_MINAMI: 'Kazuki Minami',
  KAZUMA_KODA: 'Kazuma Koda',
  KAZUMASA_YASUKUNI: 'Kazumasa Yasukuni',
  KAZUO_YAZAWA: 'Kazuo Yazawa',
  KAZUYUKI_KANO: 'Kazuyuki Kano',
  KEDAMAHADAITAI_YAWARAKAI: 'Kedamahadaitai Yawarakai',
  KEIJI_KINEBUCHI: 'Keiji Kinebuchi',
  KEIKO_FUKUYAMA: 'Keiko Fukuyama',
  KEIKO_MORITSUGU: 'Keiko Moritsugu',
  KEISIN: 'Keisin',
  KEISUKE_AZUMA: 'Keisuke Azuma',
  KEN_IKUJI: 'Ken Ikuji',
  KEN_SUGIMORI: 'Ken Sugimori',
  KEN_SUGIMORI_YUSUKE_OHMURA: 'Ken Sugimori Yusuke Ohmura',
  KENKICHI_TOYAMA: 'Kenkichi Toyama',
  KENT_KANETSUNA: 'Kent Kanetsuna',
  KENT_KANETSUNADIREC_SHINJI_HIGUCHI: 'Kent Kanetsuna/Direc. Shinji Higuchi',
  KIMIYA_MASAGO: 'Kimiya Masago',
  KINU_NISHIMURA: 'Kinu Nishimura',
  KOJI_NAKATA: 'Koji Nakata',
  KOUJI_TAJIMA: 'Kouji Tajima',
  KOUKI_SAITOU: 'Kouki Saitou',
  KRGC: 'Krgc',
  KUNIHIKO_YUYAMA: 'Kunihiko Yuyama',
  KURATA_SO: 'Kurata So',
  KUROIMORI: 'Kuroimori',
  KYOKO_KOIZUMI: 'Kyoko Koizumi',
  KYOKO_UMEMOTO: 'Kyoko Umemoto',
  LINNE: 'LINNE',
  LEE_HYUNJUNG: 'Lee HyunJung',
  LIGTON: 'Ligton',
  M_AKIYAMA: 'M. Akiyama',
  MAHOU: 'MAHOU',
  MARINA_CHIKAZAWA: 'MARINA Chikazawa',
  MINAMINAMI_TAKE: 'MINAMINAMI Take',
  MPC_FILM: 'MPC Film',
  MUGENUP: 'MUGENUP',
  MAIKO_FUJIWARA: 'Maiko Fujiwara',
  MAKOTO_IMAI: 'Makoto Imai',
  MAKURA_TAMI: 'Makura Tami',
  MANA_IBE: 'Mana Ibe',
  MARK_KRAUS: 'Mark Kraus',
  MASA: 'Masa',
  MASAHIKO_ISHII: 'Masahiko Ishii',
  MASAKAZU_FUKUDA: 'Masakazu Fukuda',
  MASAKO_TOMII: 'Masako Tomii',
  MASAKO_YAMASHITA: 'Masako Yamashita',
  MAY_DO: 'May Do',
  MEGUMI_HIGUCHI: 'Megumi Higuchi',
  MEGUMI_MIZUTANI: 'Megumi Mizutani',
  MIDORI_HARADA: 'Midori Harada',
  MIKA_PIKAZO: 'Mika Pikazo',
  MIKI_TANAKA: 'Miki Tanaka',
  MIKITANAKA: 'MikiTanaka',
  MIKIKO_TAKEDA: 'Mikiko Takeda',
  MIKIO_MENJO: 'Mikio Menjo',
  MILKY_ISOBE: 'Milky Isobe',
  MINA_NAKAI: 'Mina Nakai',
  MINAHAMU: 'Minahamu',
  MINATO: 'Minato',
  MIRANDA_BRANLEY: 'Miranda Branley',
  MISA_TSUTSUI: 'Misa Tsutsui',
  MISAKI_HASHIMOTO: 'Misaki Hashimoto',
  MITSUHIRO_ARITA: 'Mitsuhiro Arita',
  MIZUE: 'Mizue',
  MORI_YUU: 'Mori Yuu',
  MOTOFUMI_FUJIWARA: 'Motofumi Fujiwara',
  MOUSHO: 'Mousho',
  MT_TBT: 'Mt. TBT',
  MUGI_HAMADA: 'Mugi Hamada',
  MEKAYU: 'Mékayu',
  N_DESIGN_INC: 'N-DESIGN Inc.',
  NA: 'N/A',
  NC_EMPIRE: 'NC Empire',
  NABANA_KENSAKU: 'Nabana Kensaku',
  NABATAME_KAZUTAKA: 'Nabatame Kazutaka',
  NAGOMI_NIJO: 'Nagomi Nijo',
  NAKAMURA_IPPAN: 'Nakamura Ippan',
  NAKAOKA: 'Nakaoka',
  NAOKI_SAITO: 'Naoki Saito',
  NAOYO_KIMURA: 'Naoyo Kimura',
  NARANO: 'Narano',
  NARUMI_SATO: 'Narumi Sato',
  NATSUKO_SHOJI_ETE: 'Natsuko Shoji été',
  NATSUMI_MIYANOSE: 'Natsumi Miyanose',
  NATSUMI_YASHIDA: 'Natsumi Yashida',
  NATSUMI_YOSHIDA: 'Natsumi Yoshida',
  NELNAL: 'Nelnal',
  NISOTA_NISO: 'Nisota Niso',
  NOBUHIRO_IMAGAWA: 'Nobuhiro Imagawa',
  NOBUSAWAMOCHIPUYO: 'Nobusawa/Mochipuyo',
  NOBUYUKI_FUJIMOTO: 'Nobuyuki Fujimoto',
  NORIAKI_TANIMURA: 'Noriaki Tanimura',
  NORIKO_HOTTA: 'Noriko Hotta',
  NORIKO_UONO: 'Noriko Uono',
  NURIKABE: 'Nurikabe',
  OKACHEKE: 'OKACHEKE',
  OKUBO: 'OKUBO',
  OOYAMA: 'OOYAMA',
  ORBITALLINK_INC: 'ORBITALLINK Inc.',
  OKU: 'Oku',
  ORCA: 'Orca',
  OSWALDO_KATO: 'Oswaldo KATO',
  OUNISHI: 'Ounishi',
  PLANETA: 'PLANETA',
  PLANETA_CG_WORKS: 'PLANETA CG Works',
  PLANETA_HIIRAGI: 'PLANETA Hiiragi',
  PLANETA_IGARASHI: 'PLANETA Igarashi',
  PLANETA_MOCHIZUKI: 'PLANETA Mochizuki',
  PLANETA_OTANI: 'PLANETA Otani',
  PLANETA_SAITO: 'PLANETA Saito',
  PLANETA_TSUJI: 'PLANETA Tsuji',
  PLANETA_YAMASHITA: 'PLANETA Yamashita',
  PANI_KOBAYASHI: 'Pani Kobayashi',
  PO_SUZUKI: 'Po-Suzuki',
  Q_RAIS: 'Q-rais',
  REND: 'REND',
  RAITA_KAZAMA: 'Raita Kazama',
  REIKO_TANOUE: 'Reiko Tanoue',
  RIANTI_HIDAYAT: 'Rianti Hidayat',
  ROND: 'Rond',
  ROWAN_LAIDLAW: 'Rowan Laidlaw',
  RYA_UEDA: 'Rya Ueda',
  RYO_UEDA: 'Ryo Ueda',
  RYOTA_MURAYAMA: 'Ryota Murayama',
  RYOTA_SAITO: 'Ryota Saito',
  RYUTA_FUSE: 'Ryuta Fuse',
  SATOSHI_NAKAI: 'SATOSHI NAKAI',
  SIE_NANAHARA: 'SIE NANAHARA',
  SABOTERI: 'Saboteri',
  SACHI_MATOBA: 'Sachi Matoba',
  SACHIKO_ADACHI: 'Sachiko Adachi',
  SAINO_MISAKI: ['Saino Misaki', 'saino misaki'],
  SAKI_HAYASHIRO: 'Saki Hayashiro',
  SAKIKO_MAEDA: 'Sakiko Maeda',
  SANOSUKE_SAKUMA: 'Sanosuke Sakuma',
  SATOSHI_OHTA: 'Satoshi Ohta',
  SATOSHI_SHIRAI: 'Satoshi Shirai',
  SAYA_TSURUTA: 'Saya Tsuruta',
  SCAV: 'Scav',
  SEKIO: 'Sekio',
  SHIBURINGARU: 'Shiburingaru',
  SHIBUZOH: 'Shibuzoh.',
  SHIGENORI_NEGISHI: 'Shigenori Negishi',
  SHIMARIS_YUKICHI: 'Shimaris Yukichi',
  SHIN_NAGASAWA: 'Shin Nagasawa',
  SHIN_ICHI_YOSHIDA: 'Shin-ichi Yoshida',
  SHIN_ICHI_YOSHIKAWA: 'Shin-ichi Yoshikawa',
  SHINJI_HIGUCHI: 'Shinji Higuchi',
  SHINJI_HIGUCHI_NORIKO_TAKAYA: 'Shinji Higuchi + Noriko Takaya',
  SHINJI_HIGUCHI_SACHIKO_EBA: 'Shinji Higuchi + Sachiko Eba',
  SHINJI_KANDA: 'Shinji Kanda',
  SHINYA_KOMATSU: 'Shinya Komatsu',
  SHINYA_MIZUNO: 'Shinya Mizuno',
  SHIZUROW: 'Shizurow',
  SOUCHIROU_GUNJIMA: 'Souchirou Gunjima',
  SOUICHIROU_GUNJIMA: 'Souichirou Gunjima',
  STUDIO_BORA_INC: 'Studio Bora Inc.',
  SUMIYOSHI_KIZUKI: 'Sumiyoshi Kizuki',
  SUMIYOSHI_KIZUKIBIG_MAMA_TAGAWA: 'Sumiyoshi Kizuki"Big Mama" Tagawa',
  SUSUMU_MAEYA: 'Susumu Maeya',
  SUWAMA_CHIAKI: 'Suwama Chiaki',
  SYLVIA_FORREST: 'Sylvia Forrest',
  T_HONDA: 'T. Honda',
  TOKIYA: 'TOKIYA',
  TAIGA_KASAI: 'Taiga Kasai',
  TAIGA_KAYAMA: 'Taiga Kayama',
  TAIRA_AKITSU: 'Taira Akitsu',
  TAKABON: 'Takabon',
  TAKAO_UNNO: 'Takao Unno',
  TAKASHI_YAMAGUCHI: 'Takashi Yamaguchi',
  TAKESHI_NAKAMURA: 'Takeshi Nakamura',
  TAKUMI_AKABANE: 'Takumi Akabane',
  TAKUMI_WADA: 'Takumi Wada',
  TAKUYOA: ['Takuyoa', 'takuyoa'],
  TEEZIRO: 'Teeziro',
  TERADA_TERA: 'Terada Tera',
  TETSU_KAYAMA: 'Tetsu Kayama',
  TETSUO_HARA: 'Tetsuo Hara',
  TIKA_MATSUNO: 'Tika Matsuno',
  TOKUMI_AKABANE: 'Tokumi Akabane',
  TOMOAKI_IMAKUNI: 'Tomoaki Imakuni',
  TOMOHIRO_KITAKAZE: 'Tomohiro Kitakaze',
  TOMOKAZU_KOMIYA: 'Tomokazu Komiya',
  TOMOKO_WAKAI: 'Tomoko Wakai',
  TOMOMI_KANEKO: 'Tomomi Kaneko',
  TOMOMI_OZAKI: 'Tomomi Ozaki',
  TOMOWAKA: 'Tomowaka',
  TONJI_MATSUNO: 'Tonji Matsuno',
  TOSHINAO_AOKI: 'Toshinao Aoki',
  TOYSTE_BEACH: 'Toyste Beach',
  TSUYOSHI_NAGANO: 'Tsuyoshi Nagano',
  UKUMO_UITI: 'UKUMO uiti',
  USGMEN: 'USGMEN',
  ULTIMATEINUDOG: 'Ultimateinudog',
  UNINORI: 'Uninori',
  UTA: 'Uta',
  WATARU_KAWAHARA: 'Wataru Kawahara',
  WATARU_KAWAHARADIREC_SHINJI_HIGUCHI: 'Wataru Kawahara/Direc. Shinji Higuchi',
  WHISKER: 'Whisker',
  WINTR_WANDR: 'Wintr Wandr',
  YASHIRO_NANACO: 'YASHIRO Nanaco',
  YAMAZAKI_REI: 'Yamazaki Rei',
  YANO_KEIJI: 'Yano Keiji',
  YASUKI_WATANABE: 'Yasuki Watanabe',
  YOKO_HISHIDA: 'Yoko Hishida',
  YORIYUKI_IKEGAMI: 'Yoriyuki Ikegami',
  YOSHIMI_MIYOSHI: 'Yoshimi Miyoshi',
  YOSHIMOTO_YOSHIMON: 'Yoshimoto Yoshimon',
  YOSHINOBU_SAITO: 'Yoshinobu Saito',
  YOSHIOKA: 'Yoshioka',
  YOSUKE_DA_SILVA: 'Yosuke Da Silva',
  YOU_IRIBI: 'You Iribi',
  YUICHI_SAWAYAMA: 'Yuichi Sawayama',
  YUKA_MORII: 'Yuka Morii',
  YUKA_TANAKA: 'Yuka Tanaka',
  YUKIHIRO_TADA: 'Yukihiro Tada',
  YUKIKO_BABA: 'Yukiko Baba',
  YUMI: 'Yumi',
  YURI_UMEMURA: 'Yuri Umemura',
  YURIKO_AKASE: 'Yuriko Akase',
  YUSUKE_ISHIKAWA: 'Yusuke Ishikawa',
  YUSUKE_KOZAKI: 'Yusuke Kozaki',
  YUSUKE_OHMURA: 'Yusuke Ohmura',
  YUSUKE_SHIMADA: 'Yusuke Shimada',
  YUU_NISHIDA: 'Yuu Nishida',
  YUYA_OKA: 'Yuya Oka',
  ZU_KA: 'Zu-Ka',
  AKAGI: 'akagi',
  AKY_CG_WORKS: 'aky CG Works',
  AKYCG_WORKS: 'akyCG Works',
  AOKI: 'aoki',
  ASPARA: 'aspara',
  BOOOTA: 'booota',
  BUCHI: 'buchi',
  BURARI: 'burari',
  CHIBI: 'chibi',
  COCHI8I: 'cochi8i',
  DANCIAO: 'danciao',
  HANABUSHI: 'hanabushi',
  HATACHU: 'hatachu',
  HECHIMA: 'hechima',
  HNCL: 'hncl',
  IMONIII: 'imoniii',
  INOSE_YUKIE: 'inose yukie',
  KAMONABE: 'kamonabe',
  KANAHEI: 'kanahei',
  KANTARO: 'kantaro',
  KAWAYOO: 'kawayoo',
  KIRISAKI: 'kirisAki',
  KODAMA: 'kodama',
  KURUMITSU: 'kurumitsu',
  MASHU: 'mashu',
  MATAZO: 'matazo',
  MATCH: 'match',
  MELE: 'mele',
  MIKI_KUDO: 'miki kudo',
  MINGO: 'mingo',
  NAGANO: 'nagano',
  NAGIMISO: 'nagimiso',
  NISIMANA: 'nisimana',
  NISIMONO: 'nisimono',
  OKAWAMATAKATOSHI: 'okawamatakatoshi',
  OKAYAMATAKATOSHI: 'okayamatakatoshi',
  OSARE: 'osare',
  OTUMAMI: 'otumami',
  RIKA: 'rika',
  RYOMA_URATSUKA: 'ryoma uratsuka',
  SADAJI: 'sadaji',
  SATOMA: 'satoma',
  SO_TARO: 'so-taro',
  SOWSOW: 'sowsow',
  SUI: 'sui',
  SVLT: 'svlt',
  TAKASHI_SHIRAISHI: 'takashi shiraishi',
  TAKE: 'take',
  TETSUYA_KOIZUMI: 'tetsuya koizumi',
  TOI8: 'toi8',
  TONO: 'tono',
  TORIYUFU: 'toriyufu',
  WHOMOR_INC: 'whomor Inc.',
  YUU: 'yuu',
  ZIG: 'zig',
} as const;

export const CARD_VARIANT_TYPES = {
  HOLO: 'holo',
  LENTICULAR: 'lenticular',
  METAL: 'metal',
  NORMAL: 'normal',
  REVERSE: 'reverse',
} as const;

export const CARD_VARIANT_SUB_TYPES = {
  '1999_2000_COPYRIGHT': '1999-2000-copyright',
  '1999_COPYRIGHT': '1999-copyright',
  AOKI_ERROR: 'aoki-error',
  BLUE_BORDER: 'blue-border',
  D_INK_DOT_ERROR: 'd-ink-dot-error',
  ENERGY_SYMBOL_ERROR: 'energy-symbol-error',
  EVOLUTION_BOX_ERROR: 'evolution-box-error',
  GLOSSY: 'glossy',
  GOLD_BORDER: 'gold-border',
  JAPANESE_BACK: 'japanese-back',
  MISSING_EXPANSION_SYMBOL: 'missing-expansion-symbol',
  MISSING_HP: 'missing-hp',
  MISSING_RETREAT_COST: 'missing-retreat-cost',
  NO_E_READER: 'no-e-reader',
  NO_HOLO_ERROR: 'no-holo-error',
  PEELABLE_DITTO: 'peelable-ditto',
  PHANPHY_ERROR: 'phanphy-error',
  RARITY_ERROR: 'rarity-error',
  SHADOWLESS: 'shadowless',
  SHADOWLESS_RED_CHEEK: 'shadowless-red-cheek',
  SHIFTED_ENERGY_COST: 'shifted-energy-cost',
  TEXT_ERROR: 'text-error',
  UNLIMITED: 'unlimited',
} as const;

export const CARD_VARIANT_STAMPS = {
  '10TH_ANNIVERSARY': '10th-anniversary',
  '1ST_EDITION': '1st-edition',
  '1ST_EDITION_ERROR': '1st-edition-error',
  '1ST_EDITION_SCRATCH_ERROR': '1st-edition-scratch-error',
  '1ST_MOVIE': '1st-movie',
  '1ST_MOVIE_INVERTED': '1st-movie-inverted',
  '25TH_CELEBRATION': '25th-celebration',
  '30TH_POKEDAY': '30th-pokeday',
  ACE_TRAINER: 'ace-trainer',
  AKIRA_MIYAZAKI: 'akira-miyazaki',
  ASIA_2023_24: 'asia-2023-24',
  ASIA_PROMO: 'asia-promo',
  BULBASAUR: 'bulbasaur',
  CHAMPION: 'champion',
  CHARMANDER: 'charmander',
  CHASE_MOLONEY: 'chase-moloney',
  CHICAGO_2009: 'chicago-2009',
  CHRIS_FULOP: 'chris-fulop',
  CHRISTOPHER_KAN: 'christopher-kan',
  CITY_CHAMPIONSHIPS: 'city-championships',
  COMIC_CON: 'comic-con',
  COUNTDOWN_CALENDAR: 'countdown-calendar',
  CURRAN_HILL: 'curran-hill',
  D_EDITION_ERROR: 'd-edition-error',
  DAVID_COHEN: 'david-cohen',
  DESTINY_DEOXYS: 'destiny-deoxys',
  DISTRIBUTOR_MEETING: 'distributor-meeting',
  DYLAN_LEFAVOUR: 'dylan-lefavour',
  EB_GAMES: 'eb-games',
  FINALIST: 'finalist',
  FOSSIL_MUSEUM: 'fossil-museum',
  GABRIEL_FERNANDEZ: 'gabriel-fernandez',
  GAMES_EXPO: 'games-expo',
  GAMESTOP: 'gamestop',
  GEN_CON: 'gen-con',
  GREY_STAR: 'grey-star',
  GUSTAVO_WADA: 'gustavo-wada',
  GYM_CHALLENGE: 'gym-challenge',
  HIROKI_YANO: 'hiroki-yano',
  HORIZONS: 'horizons',
  IGOR_COSTA: 'igor-costa',
  ILLUSTRATION_CONTEST_2022: 'illustration-contest-2022',
  ILLUSTRATION_CONTEST_2024: 'illustration-contest-2024',
  INQUEST_GAMER: 'inquest-gamer',
  INTERNATIONAL_CHAMPIONSHIP_EUROPE: 'international-championship-europe',
  INTERNATIONAL_CHAMPIONSHIP_LATIN_AMERICA: 'international-championship-latin-america',
  INTERNATIONAL_CHAMPIONSHIP_NORTH_AMERICA: 'international-championship-north-america',
  JASON_KLACZYNSKI: 'jason-klaczynski',
  JASON_MARTINEZ: 'jason-martinez',
  JEREMY_MARON: 'jeremy-maron',
  JEREMY_SCHARFF_KIM: 'jeremy-scharff-kim',
  JESSE_PARKER: 'jesse-parker',
  JIMMY_BALLARD: 'jimmy-ballard',
  JR_STAMP_RALLY: 'jr-stamp-rally',
  JUDGE: 'judge',
  JUN_HASEBE: 'jun-hasebe',
  KEVIN_NGUYEN: 'kevin-nguyen',
  KRAZE_CLUB: 'kraze-club',
  MASTER_BALL_LEAGUE: 'master-ball-league',
  MCDONALDS: 'mcdonalds',
  MICHAEL_GONZALEZ: 'michael-gonzalez',
  MICHAEL_PRAMAWAT: 'michael-pramawat',
  MISKA_SAARI: 'miska-saari',
  MYCHAEL_BRYAN: 'mychael-bryan',
  NATIONAL_CHAMPIONSHIPS: 'national-championships',
  NINTENDO_WORLD: 'nintendo-world',
  ORIGINS: 'origins',
  ORIGINS_2008: 'origins-2008',
  PAUL_ATANASSOV: 'paul-atanassov',
  PIKACHU: 'pikachu',
  PIKACHU_TAIL: 'pikachu-tail',
  PLATINUM: 'platinum',
  PLAYER_REWARDS_PROGRAM: 'player-rewards-program',
  POKE_BALL_LEAGUE: 'poke-ball-league',
  POKEBALL: 'pokeball',
  POKEMON_4_EVER: 'pokemon-4-ever',
  POKEMON_CENTER: 'pokemon-center',
  POKEMON_CENTER_NY: 'pokemon-center-ny',
  POKEMON_DAY: 'pokemon-day',
  POKEMON_ROCKS_AMERICA: 'pokemon-rocks-america',
  POKEMON_TOGETHER: 'pokemon-together',
  POKETOUR_99: 'poketour-99',
  POP_TOURNAMENT: 'pop-tournament',
  PRE_RELEASE: 'pre-release',
  PROFESSOR_PROGRAM: 'professor-program',
  QUARTER_FINALIST: 'quarter-finalist',
  RAIN_CITY: 'rain-city',
  REED_WEICHLER: 'reed-weichler',
  REGIONAL_CHAMPIONSHIPS: 'regional-championships',
  ROSS_CAWTHORN: 'ross-cawthorn',
  SAKUYA_OTA: 'sakuya-ota',
  SCRYE: 'scrye',
  SEMI_FINALIST: 'semi-finalist',
  SET_LOGO: 'set-logo',
  SHAO_TONG_YEN: 'shao-tong-yen',
  SHUTO_ITAGAKI: 'shuto-itagaki',
  SNOWFLAKE: 'snowflake',
  SQUIRTLE: 'squirtle',
  STADIUM_CHALLENGE: 'stadium-challenge',
  STAFF: 'staff',
  STATE_CHAMPIONSHIPS: 'state-championships',
  STEPHEN_SILVESTRO: 'stephen-silvestro',
  TAKASHI_YONEDA: 'takashi-yoneda',
  THANK_YOU: 'thank-you',
  TOM_ROOS: 'tom-roos',
  TOP_EIGHT: 'top-eight',
  TOP_SIXTEEN: 'top-sixteen',
  TOP_THIRTY_TWO: 'top-thirty-two',
  TRICK_OR_TRADE: 'trick-or-trade',
  TRISTAN_ROBINSON: 'tristan-robinson',
  TSUBASA_NAKAMURA: 'tsubasa-nakamura',
  TSUGUYOSHI_YAMATO: 'tsuguyoshi-yamato',
  ULTRA_BALL_LEAGUE: 'ultra-ball-league',
  W_PROMO: 'w-promo',
  WINNER: 'winner',
  WIZARD_WORLD_CHICAGO: 'wizard-world-chicago',
  WIZARD_WORLD_PHILADELPHIA: 'wizard-world-philadelphia',
  WORLDS_2004: 'worlds-2004',
  WORLDS_2005: 'worlds-2005',
  WORLDS_2007: 'worlds-2007',
  WORLDS_2008: 'worlds-2008',
  WORLDS_2009: 'worlds-2009',
  WORLDS_2010: 'worlds-2010',
  WORLDS_2023: 'worlds-2023',
  WORLDS_2024: 'worlds-2024',
  WORLDS_2025: 'worlds-2025',
  WOTC: 'wotc',
  YUKA_FURUSAWA: 'yuka-furusawa',
  YUTA_KOMATSUDA: 'yuta-komatsuda',
  ZACHARY_BOKHARI: 'zachary-bokhari',
} as const;

export const CARD_RARITIES = {
  ACE_SPEC_RARE: 'ACE SPEC Rare',
  AMAZING_RARE: 'Amazing Rare',
  BLACK_WHITE_RARE: 'Black White Rare',
  CLASSIC_COLLECTION: 'Classic Collection',
  COMMON: 'Common',
  CROWN: 'Crown',
  DOUBLE_RARE: 'Double rare',
  FOUR_DIAMOND: 'Four Diamond',
  FULL_ART_TRAINER: 'Full Art Trainer',
  HOLO_RARE: 'Holo Rare',
  HOLO_RARE_V: 'Holo Rare V',
  HOLO_RARE_VMAX: 'Holo Rare VMAX',
  HOLO_RARE_VSTAR: 'Holo Rare VSTAR',
  HYPER_RARE: 'Hyper rare',
  ILLUSTRATION_RARE: 'Illustration rare',
  LEGEND: 'LEGEND',
  MEGA_HYPER_RARE: 'Mega Hyper Rare',
  NONE: 'None',
  ONE_DIAMOND: 'One Diamond',
  ONE_SHINY: 'One Shiny',
  ONE_STAR: 'One Star',
  PROMO: 'Promo',
  RADIANT_RARE: 'Radiant Rare',
  RARE: 'Rare',
  RARE_HOLO: 'Rare Holo',
  RARE_HOLO_LVX: 'Rare Holo LV.X',
  RARE_PRIME: 'Rare PRIME',
  SECRET_RARE: 'Secret Rare',
  SHINY_ULTRA_RARE: 'Shiny Ultra Rare',
  SHINY_RARE: 'Shiny rare',
  SHINY_RARE_V: 'Shiny rare V',
  SHINY_RARE_VMAX: 'Shiny rare VMAX',
  SPECIAL_ILLUSTRATION_RARE: 'Special illustration rare',
  THREE_DIAMOND: 'Three Diamond',
  THREE_STAR: 'Three Star',
  TWO_DIAMOND: 'Two Diamond',
  TWO_SHINY: 'Two Shiny',
  TWO_STAR: 'Two Star',
  ULTRA_RARE: 'Ultra Rare',
  UNCOMMON: 'Uncommon',
} as const;

export const CARD_CATEGORIES = {
  ENERGY: 'Energy',
  POKEMON: 'Pokemon',
  TRAINER: 'Trainer',
} as const;

export const CARD_REGULATION_MARKS = {
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
  I: 'I',
  J: ['J', 'j'],
  NONE: 'None',
} as const;

export const TCG_PLAYER_GROUPS = {
  '604': ['base1'],
  '605': ['base4'],
  '609': ['tk-dp-m'],
  '610': ['tk-dp-l'],
  '630': ['base3'],
  '635': ['base2'],
  '648': ['si1'],
  '1367': ['pl2'],
  '1368': ['dp2'],
  '1369': ['dp7'],
  '1370': ['bw10'],
  '1372': ['ecard3'],
  '1373': ['base5'],
  '1374': ['lc'],
  '1375': ['ecard1'],
  '1376': ['ex3'],
  '1377': ['ex4'],
  '1378': ['ex12'],
  '1379': ['ex13'],
  '1380': ['dp3'],
  '1381': ['hgss4'],
  '1382': ['bw9'],
  '1383': ['ex16'],
  '1384': ['pl3'],
  '1385': ['bw3'],
  '1386': ['bw5'],
  '1387': ['xy1'],
  '1389': ['neo3'],
  '1390': ['dp5'],
  '1391': ['pl4'],
  '1392': ['ex2'],
  '1393': ['ex1'],
  '1394': ['bw6'],
  '1395': ['ex14'],
  '1396': ['neo1'],
  '1397': ['ecard2'],
  '1398': ['ex10'],
  '1399': ['hgss2'],
  '1400': ['bw1'],
  '1401': ['2011bw'],
  '1402': ['hgss1'],
  '1403': ['hgss3'],
  '1404': ['ex8'],
  '1405': ['dp4'],
  '1406': ['pl1'],
  '1407': ['bwp'],
  '1408': ['bw7'],
  '1409': ['bw11'],
  '1410': ['ex9'],
  '1411': ['ex15'],
  '1412': ['bw4'],
  '1413': ['bw8'],
  '1414': ['pop7'],
  '1415': ['col1'],
  '1416': ['ex5'],
  '1417': ['dp6'],
  '1419': ['ex6'],
  '1421': ['dpp'],
  '1422': ['pop1'],
  '1423': ['np'],
  '1424': ['bw2'],
  '1426': ['dv1'],
  '1427': ['2012bw'],
  '1428': ['ex7'],
  '1429': ['ex11'],
  '1430': ['dp1'],
  '1432': ['pop6'],
  '1433': ['ru1'],
  '1434': ['neo2'],
  '1439': ['pop5'],
  '1440': ['gym2'],
  '1441': ['gym1'],
  '1442': ['pop3'],
  '1444': ['neo4'],
  '1446': ['pop9'],
  '1447': ['pop2'],
  '1450': ['pop8'],
  '1451': ['xyp'],
  '1452': ['pop4'],
  '1453': ['hgssp'],
  '1455': ['bog'],
  '1464': ['xy2'],
  '1481': ['xy3'],
  '1494': ['xy4'],
  '1509': ['xy5'],
  '1522': ['xy0'],
  '1525': ['dc1'],
  '1532': ['tk-xy-sy', 'tk-xy-n'],
  '1533': ['tk-xy-w', 'tk-xy-b'],
  '1534': ['xy6'],
  '1536': ['tk-xy-latio', 'tk-xy-latia'],
  '1538': ['tk-bw-z', 'tk-bw-e'],
  '1540': ['tk-hs-r', 'tk-hs-g'],
  '1542': ['tk-ex-p', 'tk-ex-m'],
  '1543': ['tk-ex-latio', 'tk-ex-latia'],
  '1576': ['xy7'],
  '1661': ['xy8'],
  '1692': ['2014xy'],
  '1694': ['2015xy'],
  '1701': ['xy9'],
  '1728': ['g1'],
  '1780': ['xy10'],
  '1796': ['tk-xy-su', 'tk-xy-p'],
  '1815': ['xy11'],
  '1842': ['xy12'],
  '1861': ['smp'],
  '1863': ['sm1'],
  '1919': ['sm2'],
  '1938': ['xya'],
  '1957': ['sm3'],
  '2054': ['sm3.5'],
  '2069': ['tk-sm-l', 'tk-sm-r'],
  '2071': ['sm4'],
  '2148': ['2017sm'],
  '2178': ['sm5'],
  '2209': ['sm6'],
  '2278': ['sm7'],
  '2295': ['sm7.5'],
  '2328': ['sm8'],
  '2364': ['2018sm'],
  '2377': ['sm9'],
  '2409': ['det1'],
  '2420': ['sm10'],
  '2464': ['sm11'],
  '2480': ['sm115'],
  '2534': ['sm12'],
  '2545': ['swshp'],
  '2555': ['2019sm'],
  '2585': ['swsh1'],
  '2626': ['swsh2'],
  '2675': ['swsh3'],
  '2685': ['swsh3.5'],
  '2701': ['swsh4'],
  '2754': ['swsh4.5'],
  '2765': ['swsh5'],
  '2807': ['swsh6'],
  '2848': ['swsh7'],
  '2867': ['cel25'],
  '2906': ['swsh8'],
  '2948': ['swsh9'],
  '3040': ['swsh10'],
  '3064': ['swsh10.5'],
  '3087': ['2016xy'],
  '3118': ['swsh11'],
  '3170': ['swsh12'],
  '17688': ['swsh12.5'],
  '22873': ['sv01', 'svp'],
  '23120': ['sv02'],
  '23228': ['sv03'],
  '23237': ['sv03.5'],
  '23286': ['sv04'],
  '23353': ['sv04.5'],
  '23381': ['sv05'],
  '23473': ['sv06'],
  '23529': ['sv06.5'],
  '23537': ['sv07'],
  '23651': ['sv08'],
  '23821': ['sv08.5'],
  '24073': ['sv09'],
  '24269': ['sv10'],
  '24325': ['sv10.5b'],
  '24326': ['sv10.5w'],
  '24380': ['me01'],
  '24448': ['me02'],
  '24541': ['me02.5'],
  '24587': ['me03'],
  '24655': ['me04'],
  '24688': ['me05'],
} as const;
