name: Update DB schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  trigger-update-db:
    name: Trigger update DB
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/update-db.yml