name: Update DB

on:
  workflow_dispatch:
# TODO: revert
#    inputs:
#      branch:
#        description: 'Name of branch to create'
#        type: string
#        required: true
#        default: update-db
#      force_update:
#        description: 'Force update'
#        type: boolean
#        required: false
#        default: false
#      create_pr:
#        description: 'Create a PR with the changes'
#        type: boolean
#        required: true
#        default: true
  workflow_call:
    inputs:
      branch:
        description: 'Name of branch to create'
        type: string
        required: true
        default: update-db
      force_update:
        description: 'Force update'
        type: boolean
        required: false
        default: false
      create_pr:
        description: 'Create a PR with the changes'
        type: boolean
        required: true
        default: true
  schedule:
    - cron: '0 0 * * *'

env:
  FORCE_UPDATE: ${{ inputs.force_update }}

jobs:
  # Ensure inputs get passed to workflow when triggered via a schedule
  trigger-update-db:
    name: Trigger update DB
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' # todo only run on schedule
    uses: ./.github/workflows/update-db.yml

  update-db:
    name: Update DB
    if: github.event_name == 'workflow_call' # todo also run on workflow_dispatch
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push db changes
      pull-requests: write # to create pull request
    steps:
      - name: Checkout existing DB update branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # avoid cache poisoning
      - name: Try applying changes from ${{ inputs.branch }}
        run: |
          git fetch origin
          git cherry-pick -n "origin/${{ inputs.branch }}" || true
      - name: Install dependencies
        run: npm ci
      - name: Update DB
        id: update_db
        run: |
          UPDATE_DB_RESULT=$(npm run update-db -s)
          echo "Result: ${UPDATE_DB_RESULT}"
          echo "has_changes=$(echo "${UPDATE_DB_RESULT}" | jq -r ".hasChanges")" >> $GITHUB_OUTPUT
          echo "message=$(echo "${UPDATE_DB_RESULT}" | jq -r ".message")" >> $GITHUB_OUTPUT
      - name: Update test snapshots
        if: steps.update_db.outputs.has_changes == 'true'
        run: npm test -- --update
      - name: Run prettier
        if: steps.update_db.outputs.has_changes == 'true'
        run: npm run prettier:fix
      - name: Create changeset
        if: steps.update_db.outputs.has_changes == 'true'
        run: |
          npm run delete-stale-changesets
          npx changeset add -m "${{ steps.update_db.outputs.message }}" --patch @tcgdata/tcgdex-offline
      - name: Create or Update Pull Request
        if: steps.update_db.outputs.has_changes == 'true' && inputs.create_pr == 'true
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: ${{ steps.update_db.outputs.message }}'
          branch: ${{ inputs.branch }}
          base: main
          title: ${{ steps.update_db.outputs.message }}
          body: 'This PR was automatically created or updated by a GitHub Action.'
          delete-branch: true
